baseURL = "https://bryutus.github.io/"
title = "お前もか"
author = false
paginate = 10
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "harbor"

[Author]
  name = "bryutus"

[permalinks]
  post = "/:year/:month/:day/:filename/"
  page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user-circle fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tags fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "/archives/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "Twitter"
  url="https://twitter.com/bryutus"
  icon="fab fa-twitter"

[[params.social]]
  name= "GitHub"
  url="https://github.com/bryutus"
  icon="fab fa-github"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"
